### ISSUE TITLE
Support for LG G2 VS980 stock rom via root

### ISSUE THREAD

**Issue by AidanRB** [42SK/TVKILL#10]
ConsumerIrManager is not installed, as the IR transmitter isn't supposed to be accessible by third party apps.  The QRemote API doesn't exist, either.  The preinstalled Quick Remote app appears to be the only thing able to access the IR.  Other apps can't even tell it exists.  Can you still send IR signals via root?  LG G2 VS980, upgraded to Lollipop OTA.

**Comment by 42SK** [comment]
What makes you think that the ```ConsumerIrManager``` is "not installed"? It's actually part of the standard Android API and should therefore be available on every device running Android 4.4 or higher.
Does **TV KILL** display the "IR emitter found" toast-message at the bottom of the screen when you start the application?
Have you been able to transmit IR patterns with other third party apps or is this a general problem?
And how exactly did you determine whether or not the QRemote API is supported on your device?

**Comment by AidanRB** [comment]
No third party apps can tell that the IR beamer exists.  Verizon locked it down so that third parties can't access it.  Also, looking at the developer page on the QRemote API, I saw a list that said LG G2 was supported.  It then listed versions of the phone which had it, among which was not VS980.  When I open TV Kill, it gives me a message saying there's no IR beamer.  This problem is, as far as I know, unique to the VS980.

**Comment by 42SK** [comment]
OK, thanks a lot for informing me about this.
I had already heard of some LG devices that don't allow third party apps to transmit IR patterns, but I wasn't sure which devices are affected by this.
I don't think that there's much we can do programmatically to solve this issue, since LG seems to have intentionally locked down the IR blaster on the VS980.
However, there might be a way to bypass these restrictions.
The most plausible solution I can think of would be to [install CyanogenMod on your device](http://wiki.cyanogenmod.org/w/Install_CM_for_vs980) (see issue #6 for more information). I cant guarantee that that will solve the problem, but it's definitely worth a try.
