### ISSUE TITLE
Display IR activity; debug UI for geeks

### ISSUE THREAD

**Issue by a-raccoon** [42SK/TVKILL#11]
Would it be possible to show live/raw activity of the IR blaster doing its thing (blinking on/off) as well as a cycling queue of which pattern is currently being played and which patterns are coming up next?  Or are the instructions sent off to the API asynchronously?

**Comment by 42SK** [comment]
I already thought about replacing the spinning progress bar with a real horizontal progress bar that indicates how many patterns have already been sent. In addition to that, one could also display the brand of the  pattern that is currently being transmitted.
As for showing the live activity of the IR blaster, I don't think that this would make much sense, since the on/off cycles are quite fast. However, some devices automatically indicate IR activity by flashing the phone's notification LED whenever a pattern is sent.

**Comment by a-raccoon** [comment]
If you show the brand(s) of the pattern currently being played, could you also display the pattern's code (is in hexadecimal?) so the user might look it up and note which codes work and approximate the code sets that are compatible with their equipment, etc?

I also understand multiple manufacturers will use/share the same somewhat standardized code sets for power or volume and other common controls, so I can image some groupings may occur.

**Comment by 42SK** [comment]
I can confirm your assumption that some patterns affect multiple brands, since **TV KILL** is also capable of turning off LOEWE TVs, although it doesn't transmit any specific patterns for that brand.
The patterns used by **TV KILL** are all expressed in periods of the carrier frequency (they're not coded in hexadecimal).
Showing the patterns while they are being transmitted is probably not such a good idea, since they are sent very rapidly (in addition to that, they're also [rather long](https://github.com/42SK/TVKILL/blob/master/app/src/main/java/com/redirectapps/tvkill/BrandContainer.java)).
However, you can still look up patterns in the source code (they shouldn't be too hard to find if you know the brand).

**Comment by NeverMine17** [comment]
@42SK, How about hash?
That could be useful.
Even though it doesn't say the exact value.
Look up CRC-32.
