### ISSUE TITLE
Any plans to expand to a full universal remote?

### ISSUE THREAD

**Issue by kq01526** [42SK/TVKILL#14]
Hi @42SK ,

do you have any plans to expand your remote to a full universal remote (i.e. a remote that can do more than just powering down TVs)?

As far as I can tell there is no open source universal remote app available for Android, right?

I found this Irdroid:

https://github.com/Irdroid/Irdroid

But Irdroid seems to require an external IR blaster...

So, would be appreciated if you could comment on this.

Regards

**Comment by 42SK** [comment]
Hello @kq01526,
as I already pointed out in issue #1, **TV KILL** was actually never intended to be a "full" universal remote:
> [...] one should keep in mind that the main goal of **TVKILL** is not to become a fully featured IR-Remote with all the capabilities of a regular remote. **TVKILL** is intended to be a amusement tool that can either be used to play pranks on others (by turning off TVs) or to encourage responsible TV watching (**TVKILL** was mostly inspired by the [TV-B-Gone-Remote](https://wikipedia.org/wiki/TV-B-Gone)).

Hence, most future contributions will solely aim to serve the project's original purpose.
However, since anyone is permitted to [modify and redistribute](https://github.com/42SK/TVKILL/blob/master/LICENSE) **TV KILL**, one could theoretically create a new project based on **TV KILL**, which could then be expanded to a "full" universal remote.
I personally wouldn't have the time to maintain such a project, but perhaps somebody else is interested in creating a new open source remote app.
As for other FOSS remote project/libraries, I have only found one so far, but it seems to be rather outdated:
https://github.com/timnew/AndroidInfrared
