### ISSUE TITLE
Feature Request: REDUCE volume, not Mute

### ISSUE THREAD

**Issue by jimmiles** [42SK/TVKILL#27]
The 'experimental' mute button works. Every time (multiple TV models). Would it be possible to get a button to reduce the volume instead of muting it? For example, cutting volume in half? 
I love the app. You rock my world for making it available. Thank you! I would use it more-- every day, almost, at work where I'm plagued by TVs in my break rooms cranked up to f**king ELEVEN, with this feature.

**Comment by 42SK** [comment]
Theoretically, yes, a "decrease volume" button would be possible. However, since most TVs only reduce the volume gradually, a "cut-volume-to-half" button - like the one you are describing - is not. The button would only be capable of reducing the volume on step at a time, meaning that you'd have to hit it several times before one would actually notice a difference. Since the app has to send IR-patterns for several different TV models, it would take ages until the volume finally reaches the desired level.
Hence, I'm afraid your proposal is not very practical.
