### ISSUE TITLE
Add support for Android 4.0.4

### ISSUE THREAD

**Issue by pizzamaker** [42SK/TVKILL#4]
Pretty please?

**Comment by 42SK** [comment]
I'm afraid that's not possible.
TV KILL uses Android's [ConsumerIrManager class](https://developer.android.com/reference/android/hardware/ConsumerIrManager.html) to transmit IR-patterns. That class requires [API level 19](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels) (Android 4.4) or higher.
We'd love it if TV KILL could also run Android devices which are a bit older, but this class is of vital importance to the application, and since it is not available on older Android versions, there is simply no way of adding support for anything below Android 4.4.

However, you can still try to upgrade your Android version.
If your device's manufacturer doesn't provide any upgrades, you might still be able to obtain a newer Android version by flashing an alternate firmware, for example [CyanogenMod](http://www.cyanogenmod.org/).

**Comment by locutis-of-borg-1999** [comment]
There are quite a few reasons to have Cyanogenmod, or, perhaps better, Replicant; ti fully control ones own hardware.  But, that's nit alwas possible.  :-(
