### ISSUE TITLE
LG G2 with CM

### ISSUE THREAD

**Issue by sniperle** [42SK/TVKILL#6]
I'm using the F-Droid build on LG G2 with the latest CyanogenMod 12.1 nightly, but the IR-Diode isn't sending out any signal. The app detects an IR-Blaster at startup. According to the changelog of CM the IR-Blaster is supported on the LG G2 now: http://review.cyanogenmod.org/#/c/111554/

Maybe a logcat helps:
10-25 15:11:43.672 I/ActivityManager(819): START u0 {act=android.intent.action.VIEW dat=https://github.com/42SK/TVKILL cmp=org.mozilla.fennec_fdroid/.App} from uid 10137 on display 0
10-25 15:19:59.591 I/Timeline(2123): Timeline: Activity_launch_request id:com.redirectapps.tvkill time:13823519
10-25 15:19:59.592 I/ActivityManager(819): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.redirectapps.tvkill/.MainActivity (has extras)} from uid 10009 on display 0
10-25 15:19:59.620 V/WindowManager(819): addAppToken: AppWindowToken{16a1519 token=Token{29c0ec60 ActivityRecord{1ff10863 u0 com.redirectapps.tvkill/.MainActivity t2581}}} to stack=1 task=2581 at 0
10-25 15:19:59.623 V/WindowManager(819): Adding window Window{2bc3e778 u0 Starting com.redirectapps.tvkill} at 12 of 18 (after Window{2ce1cd34 u0 org.mozilla.fennec_fdroid/org.mozilla.fennec_fdroid.App})
10-25 15:19:59.673 I/ActivityManager(819): Start proc 12821:com.redirectapps.tvkill/u0a15 for activity com.redirectapps.tvkill/.MainActivity
10-25 15:19:59.818 V/WindowManager(819): Adding window Window{eea7e8d u0 com.redirectapps.tvkill/com.redirectapps.tvkill.MainActivity} at 12 of 19 (before Window{2bc3e778 u0 Starting com.redirectapps.tvkill})
10-25 15:19:59.943 I/ActivityManager(819): Displayed com.redirectapps.tvkill/.MainActivity: +299ms
10-25 15:20:00.142 I/Timeline(819): Timeline: Activity_windows_visible id: ActivityRecord{1ff10863 u0 com.redirectapps.tvkill/.MainActivity t2581} time:13824070
10-25 15:20:02.149 W/PackageManager(1592): Failure retrieving resources for com.redirectapps.tvkill: Resource ID #0x0
10-25 15:20:06.464 V/WindowManager(819): Adding window Window{3028f6b5 u0 Starting com.nolanlawson.logcat} at 13 of 19 (after Window{eea7e8d u0 com.redirectapps.tvkill/com.redirectapps.tvkill.MainActivity})
10-25 15:20:24.449 I/Timeline(819): Timeline: Activity_windows_visible id: ActivityRecord{1ff10863 u0 com.redirectapps.tvkill/.MainActivity t2581} time:13848377
10-25 15:20:28.235 W/PackageManager(1592): Failure retrieving resources for com.redirectapps.tvkill: Resource ID #0x0

**Comment by 42SK** [comment]
This might be quite a serious bug.
It must admit, I never had the opportunity to test TV KILL on a LG-device.
However, I have tested it on devices running CyanogenMod 12.1 and it never seemed to cause any problems.
I can't say for certain why your phone doesn't transmit anything, but I'd assume it is because it's from LG, although I am not aware of any difference between LG and other brands when it comes to transmitting IR-patterns.

I'll see if I can do anything, but just to be sure, are you certain that your phone really doesn't transmit **anything** and that you IR-blaster is working?
If not, you should be able to notice whether the blaster is working or not by trying out other remote-apps and/or by [checking your IR-blaster with a digital camera](http://www.wikihow.com/See-Infared-Light).

Any comments that might help us to solve this problem are deeply appreciated.

**Comment by sniperle** [comment]
Thanks for your help. :-) I checked it a few days ago with another phone (camera), but to be sure I will recheck it again later and then post if the IR-Blaster is transmitting a signal or not.

**Comment by 42SK** [comment]
I think I've found something that might be useful.
There is a SDK from LG named [QRemote](http://developer.lge.com/resource/mobile/RetrieveOverview.dev?categoryTypeCode=ANRS#RS00000802) that can be used to transmit IR signals on several LG devices, including the G2.
I suppose LG doesn't support Android's [ConsumerIrManager](http://developer.android.com/reference/android/hardware/ConsumerIrManager.html) class (which is used by **TV KILL**), because they want developers to use their own SDK instead.
It might be possible to support LG devices by using this SDK. However, I am not sure if the API can be used along with the [GNU General Public Licence](https://www.gnu.org/licenses/gpl.html), so I'll try to find out if the API somehow interferes with TV KILL's [licence](https://github.com/42SK/TVKILL/blob/master/LICENSE). If not, we can try to solve this issue by implementing it.
I also can't say for certain that the API works on devices running CyanogenMod.
If anyone else has already used TV KILL on a LG phone our knows more about using the IR emitter on LG devices, please write a comment.

**Comment by sniperle** [comment]
Thanks again for analyzing the problem. Then I wonder for what CMs blaster change from the first is. Hopefully the implementation of LG support is possible.

**Comment by 42SK** [comment]
@sniperle 
Have you checked your IR-Blaster by now?
It actually sounds rather unlikely that CyanogenMod is depending on a proprietary LG framework to transmit IR patterns.
I thought that we might be having a similar problem on HTC devices in issue #8, but it turns out that one can use TV KILL on HTC devices running CyanogenMod, although HTC also has its own IR API.

**Comment by sniperle** [comment]
@42SK: Thanks for your message and sorry for the delay. 
Yes, I tested it again with a second phone, a camera and another remote control.  And sadly no IR transmission from my phone. 
According to the changlog of CM the used IR librarys are: 
lib/hw/consumerir.msm8974.so
lib/libcir_driver.so

**Comment by 42SK** [comment]
@sniperle 
I had a look at the */system/lib* directory on a Samsung Galaxy S4 with CyanogenMod 12.1.
I was able to find the *hw/consumerir.msm8974.so* library, and TV KILL works flawlessly on this device.
I therefore assume that the ConsumerIrManager should usually work on your device too.
Have you ever noticed a small [toast-message](https://developer.android.com/guide/topics/ui/notifiers/toasts.html) at the bottom of the screen when you start the application? TV KILL should display this toast when it detects your IR blaster.

**Comment by sniperle** [comment]
Yes I can see this toast message.
I will try to test or with another G2, hopefully today I will be able to catch up one.
Will report after the test.

**Comment by sniperle** [comment]
Tested with another G2 and CM12.1.
Same here, I can see the toast message but the IR diode isn't sending out anything. 😕

**Comment by 42SK** [comment]
OK,
I could think of a few reasons why this is not working: 
* The ConsumerIrManager works on your device but TV KILL is somehow not using it correctly. (e.g. the patterns aren't converted the way they should be)
* The LG API is required to transmit IR patterns on your device. (unlikely, since you are using CyanogenMod and not the original firmware)
* CyanogenMod doesn't support your IR-blaster. (I know that the [changelog](http://review.cyanogenmod.org/#/c/111554/) suggests otherwise, but they seem to have added support quite recently, so it's hard to tell if it really works flawlessly. There are several older threads on various forums in which users complain that there IR-blaster doesn't work on the [G2](http://forum.xda-developers.com/showthread.php?t=2536131) and the [G3](http://forum.cyanogenmod.org/topic/109975-ir-blaster-doesnt-work/) when running CM.)
* The IR blasters of the devices @sniperle tested are both broken. (very unlikely)

@sniperle, have you ever tried to use your IR blaster with a different application?
If you are unable to transmit any IR signals in general, it might be a good idea to ask a CyanogenMod developer about this. I could try to contact the developer who added the IR blaster support on the G2 if this is a general problem.

**Comment by sniperle** [comment]
Yes, I tried a few Apps from the Play Store which where described to work with a G3 (and others). Didin't test them with a camera but my TV did nothing, so I assume the IR was not sending anything too.

**Comment by 42SK** [comment]
OK, then there's probably something wrong with CyanogenMod.
The developer who added IR blaster support seems to be @intervigilium, I'll try to inform him about this.

**Comment by 42SK** [comment]
I asked the developer who added the IR support to the G2 about this. According to him, LG seems to provide some kind of hardware abstraction layer for the IR blaster, which should support the ConsumerIrManager.
Therefore, assuming that he is right, TV KILL should also work on your device.
However, [some people claim that LG restricts access to the IR blaster for third party apps](http://forums.androidcentral.com/verizon-lg-g2/317853-any-ir-remote-apps-work-g2.html#post3098326).
I assume that the applications that have implemented the proprietary LG API can use the IR blaster by now.
I also found an [app description on Google Play](https://play.google.com/store/apps/details?id=jw.ir.remote.control&hl=en) that confirms this:
>"[...] [The] LG G2 is not supported since it use[es] an own proprietary closed interface rather than [the] standard Android interface."

I don't know for certain that these restrictions also affect devices running CyanogenMod, but the developer I asked did mention the possibility that the HAL might be relying on "some other service", and since **TV KILL** was not the only application that didn't work on your device, it does seem quite probable.
For now, we can only hope that the ConsumerIrManager will one day work on your device.
Until then, you might be able to use your IR blaster with the IR application from your original ROM ([this thread](http://forum.xda-developers.com/showthread.php?t=2515141) should help you install it).

**Comment by sniperle** [comment]
Alright and thank you very much :-)

**Comment by sniperle** [comment]
FYI: now working on the LG G2
http://review.cyanogenmod.org/#/c/129233/

**Comment by 42SK** [comment]
Great! I'm glad that somebody finally managed to fix this.

**Comment by AidanRB** [comment]
I'm just wondering, will TV Kill get support for the default LG G2 rom (lollipop via ota) via root?  If you'd like logs or information about the system or anything, feel free to ask me.  I can try to help to the best of my ability.

**Comment by 42SK** [comment]
@AidanRB 
Actually, **TV KILL** should already support most LG devices.
The [LG developer site](http://developer.lge.com/resource/mobile/RetrieveOverview.dev?categoryTypeCode=ANRS#supporteddev) claims:
>"[The G2] support[s] the QRemote SDK (as well as Android ConsumerIrManager APIs)"

Since **TV KILL** uses the ```ConsumerIrManager``` to transmit IR patterns, I see no reason why it shouldn't work on your device.
However, if you do happen to encounter any problems, feel free to open a new thread and I'll see what I can do.
