### ISSUE TITLE
How to add more patterns

### ISSUE THREAD

**Issue by Natureshadow** [42SK/TVKILL#7]
Killing TVs is good, but killing more TVs is better. I've yet stumbled upon a Grundig TV set that did not react to the shipped patterns.

What about crowdsourcing more? If the Android IR thing can also receive IR, recording patterns from an actual remote is easy. If not, one could publish a tiny Arduino-based circuit and code to produce necessary data.

**Comment by 42SK** [comment]
That is a very good idea.
I wanted add a entry to this project's wiki that explains how one can add patterns for new TVs anyway.
The Arduino idea is also great, I've already spent hours searching for IR-pattern-databases that also contains patterns for brands like Grunding, but they are almost non-existent. There seem to be a few Arduino [tutorials](https://learn.adafruit.com/using-an-infrared-library/hardware-needed) an [libraries](https://github.com/cyborg5/IRLib/) for decoding IR-patterns, it would really help a lot if we could use one of them to add more IR patterns to TV KILL.
I'll work on that wiki entry, so that anyone who finds a TV that is not supported yet will be able to add it's pattern to the application.

**Comment by Natureshadow** [comment]
I'd very much like to pass this to Teckids e.V., a youth tinkering and open source organisation. The kids could build an Arduino board and program for this which could be published here.

**Comment by 42SK** [comment]
Sure, no problem!
It would be great if you came up with a project that could help people to add more patterns to TV KILL.

**Comment by spangey** [comment]
Love the sentiment. Talking to ppl here about dedicating a small amount of time to the possibility of fleshing this out some and either forking or shooting a pull request your way. Good stuff!

**Comment by 42SK** [comment]
I added an [entry to the projects Wiki](https://github.com/42SK/TVKILL/wiki/How-to-add-IR-patterns-to-TV-KILL) that explains how one can add patterns to **TV KILL**.
